### ISSUE TITLE
`JsonException` when creating `MLEdgeModel`

### ISSUE THREAD

**Issue by bluebright** [natmlx/natml-unity#58]
Sorry for my bad english ...

- My Project
  - Unity Editor Ver : 2021.3.24f1
  - Target : Android Device 
  - Using package
    - AR Foundation 4.2.7
    - UniTask
  
- Try package
  - "ai.natml.natml": "1.1.4","1.1.5","1.1.6"
  - "Newtonsoft.Json" : "3.1" <= (NatML Dependency), "13.0.3"
  - "ai.natml.vision.mobilenet-v2": "1.0.2", "1.0.3"
  - "ai.natml.natml.arfoundation": "1.0.2" (Not using videokit)
  
- Try Tutorial (Create NatML Hub Key already)
	- https://docs.natml.ai/unity/prelims/getting-started
	- https://github.com/natmlx/natml-unity#installing-natml
	- https://github.com/natmlx/mobilenet-v2-unity
	- https://github.com/natmlx/mobilenet-v2-unity/blob/main/Packages/ai.natml.vision.mobilenet-v2/README.md

- Error code in Android Logcat for unity
```
Error Unity JsonException: No parameterless constructor defined for 'NatML.API.Graph.GraphEnum`1[NatML.API.Types.GraphFormat]'.
Error Unity   at Newtonsoft.Json.Serialization.JsonTypeReflector+<>c__DisplayClass22_0.<GetCreator>b__0 (System.Object[] parameters) [0x00090] in \root\repo\Src\Newtonsoft.Json\Serialization\JsonTypeReflector.cs:267 
Error Unity   at Newtonsoft.Json.Serialization.JsonTypeReflector.GetJsonConverter (System.Object attributeProvider) [0x00025] in \root\repo\Src\Newtonsoft.Json\Serialization\JsonTypeReflector.cs:191 
Error Unity   at Newtonsoft.Json.Serialization.DefaultContractResolver.SetPropertySettingsFromAttributes (Newtonsoft.Json.Serialization.JsonProperty property, System.Object attributeProvider, System.String name, System.Type declaringType, Newtonsoft.Json.MemberSerialization memberSerialization, System.Boolean& allowNonPublicAccess) [0x002f8] in \root\repo\Src\Newtonsoft.Json\Serialization\DefaultContractResolver.cs:1618 
Error Unity   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperty (System.Reflection.MemberIn
```

- My Code ex...

```cs
private async void Start()
{
   ...
		
    //The predictor is Global variable		
    if (predictor == null)
    {
        // I also try code in UniTask
        predictor = await MobileNetv2Predictor.Create();
    }

    ...
		
}
```

I Just try following tutorial but not working at creation code. I wonder what I'm missing?

**Comment by olokobayusuf** [comment]
Hey @bluebright , this looks like a bug in our implementation. Gonna push an update that fixes it in about an hour.

**Comment by olokobayusuf** [comment]
[Fixed in 1.1.7](https://github.com/natmlx/natml-unity/releases/tag/1.1.7).

**Comment by bluebright** [comment]
Sorry to bother you...
I tried again with the updated version, but unfortunately the error still occurred.

- Unity 2022.3.4f1
- NatML : 1.1.7 and 1.1.8
- mobilenet-v2 : 1.0.3

- Error message in Android logcat for unity
```cs
Error Unity JsonSerializationException: Unable to find a constructor to use for type NatML.API.Graph.GraphResponse`1[NatML.API.Types.PredictorSession]. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'errors', line 1, position 10.
Error Unity   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract objectContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, Newtonsoft.Json.Serialization.JsonProperty containerProperty, System.String id, System.Boolean& createdFromNonDefaultCreator) [0x00000] in <00000000000000000000000000000000>:0 
Error Unity   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerCont
```

**Comment by olokobayusuf** [comment]
Hey @bluebright are you using stripping? In `Project Settings > Player Settings`, can you share a screenshot of your stripping and iL2CPP configuration?

**Comment by bluebright** [comment]
Sorry for late answer and Thank you for update NatML.
I try 1.1.11 version but still didn't work.

I check my ```Project Settings > Player Settings``` your mentions, the option of ```Managed Stripping Level``` is set to ```High```.
JsonException is not occured when ```Managed Stripping Level``` is change "High" to "Minimal". (and "mobilenet-v2" tutorial is now working.)

Thank you for sharing a tip.


Upload my player setting (That option may have been changed to run "ARCore Foundation".)

![Cap 2023-07-04 09-44-09-250](https://github.com/natmlx/natml-unity/assets/12007202/6279d866-3542-4e46-ba66-5039fe500d7b)

![Cap 2023-07-04 09-44-50-351](https://github.com/natmlx/natml-unity/assets/12007202/500af60e-82d6-47bc-a882-c9b8a7d70bd2)

![Cap 2023-07-04 09-45-15-903](https://github.com/natmlx/natml-unity/assets/12007202/ac00f3e9-738b-4f1c-b421-a9ad4094e268)

**Comment by olokobayusuf** [comment]
I recommend using the low managed stripping setting as a workaround for now. We'll revisit this in the next update.

**Comment by olokobayusuf** [comment]
This has been properly fixed in [1.1.12](https://github.com/natmlx/natml-unity/releases/tag/1.1.12). You can now use the highest managed stripping setting without running into the `JsonException`. Thank you for helping investigate this issue @bluebright ❤️
